apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wprh0122p-go
  janus-idp.io/tekton: wprh0122p-go
  backstage.io/kubernetes-id: wprh0122p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wprh0122p-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
